/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'ocean-deep': '#0F172A',
        'teal-600': '#0D9488',
        'teal-700': '#0F766E',
        'cyan-400': '#22D3EE',
        'cyan-500': '#06B6D4',
        'warm-sand': '#E6D5B8',
        'coral': '#FF6B6B',
        'coral-light': '#FF8585',
        'coral-dark': '#FF8A8A',
        'mist-white': '#F8FAFC',
        'slate-400': '#94A3B8',
        'slate-700': '#334155',
        'slate-800': '#1E293B',
        // Theme-aware CSS variable colors
        'theme-primary': 'var(--theme-primary)',
        'theme-secondary': 'var(--theme-secondary)',
        'theme-accent': 'var(--theme-accent)',
        'theme-background': 'var(--theme-background)',
        'theme-surface': 'var(--theme-surface)',
        'theme-text': 'var(--theme-text)',
        'theme-text-muted': 'var(--theme-text-muted)',
        'theme-card-bg': 'var(--theme-card-bg)',
        'theme-hero-bg': 'var(--theme-hero-bg)',
        'theme-footer-bg': 'var(--theme-footer-bg)',
        'theme-border': 'var(--theme-border)',
        'theme-button': 'var(--theme-button)',
        'theme-button-hover': 'var(--theme-button-hover)',
        'theme-wave': 'var(--theme-wave)',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'montserrat': ['Montserrat Variable', 'sans-serif'],
        'inter': ['Inter Variable', 'sans-serif'],
        'theme-heading': ['var(--theme-font-heading)', 'sans-serif'],
        'theme-body': ['var(--theme-font-body)', 'sans-serif'],
      },
      spacing: {
        'section-desktop': '120px',
        'section-mobile': '64px',
        'content-pad': '24px',
        'content-pad-mobile': '16px',
      },
      maxWidth: {
        'content': '1280px',
      },
      borderRadius: {
        'card': '24px',
        'button': '14px',
        'input': '12px',
        'image': '16px',
        'pill': '9999px',
        'panel': '32px',
        'theme-card': 'var(--theme-radius-card)',
        'theme-button': 'var(--theme-radius-button)',
        'theme-image': 'var(--theme-radius-image)',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        'card': '0 8px 32px rgba(15, 23, 42, 0.12)',
        'card-hover': '0 16px 48px rgba(15, 23, 42, 0.18)',
        'button': '0 4px 16px rgba(255, 107, 107, 0.35)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.15)',
        'nav': '0 2px 20px rgba(15, 23, 42, 0.08)',
        'theme-card': 'var(--theme-shadow-card)',
        'theme-button': 'var(--theme-shadow-button)',
        'theme-nav': 'var(--theme-shadow-nav)',
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
